version: '2'

services:
  sedaily-api:
    image: softwaredaily/sedaily-rest-api
    container_name: sedaily-rest-api
    ports:
      - "4040:4040"
    depends_on:
      - mongo
    restart: always
  mongo:
    image: softwaredaily/sedaily-mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
