language: node_js
os: linux
node_js:
  - "10"
addons:
  apt:
    packages:
      # https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
      - libgconf-2-4
services:
  - docker
git:
  depth: 3
stages:
  - lint
  - test
  - name: docker
    if: branch = develop AND type = push
matrix:
  include:
    - stage: lint
      script:
        - npm run lint || travis_terminate 1
        - npm run build:dev || travis_terminate 1
    - stage: test
      before_script:
        - npm run backend:start
      script:
        - npm run test:e2e
    - stage: docker
      script:
        - ./devops/build-image.sh || travis_terminate 1
cache:
  npm: true
  directories:
    - ~/.npm
    - ~/.cache
